# Generated by Django 4.0.6 on 2022-07-20 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import employees.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Access Right Name')),
                ('backoffice', models.BooleanField(default=True, verbose_name='Back Office Access')),
                ('cashier', models.BooleanField(default=True, verbose_name='Cashier Access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access Right',
                'verbose_name_plural': 'access Rights',
                'db_table': 'rights',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Employee Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('pin', models.CharField(max_length=4, verbose_name='Cashier PIN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('right', models.ForeignKey(limit_choices_to=employees.models.Employees.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='employees.rights', verbose_name='Access Right')),
                ('shops', models.ManyToManyField(limit_choices_to=employees.models.Employees.limit_choices_to_current_user, to='shops.shops', verbose_name='Shops')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'db_table': 'employees',
            },
        ),
    ]
