# Generated by Django 4.0.6 on 2022-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rights',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
