# Generated by Django 4.0.6 on 2022-07-19 04:43

from django.db import migrations, models
import employees.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Employee Name'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='shops',
            field=models.ManyToManyField(limit_choices_to=employees.models.Employees.limit_choices_to_current_user, to='shops.shops'),
        ),
    ]
