# Generated by Django 4.0.6 on 2022-07-19 05:49

from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('items', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipts',
            name='cashier',
            field=models.ForeignKey(limit_choices_to=sales.models.Receipts.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='shops.cashiers', verbose_name='Cashier'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='shop',
            field=models.ForeignKey(limit_choices_to=sales.models.Receipts.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='shops.shops', verbose_name='Shop'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='category',
            field=models.ForeignKey(limit_choices_to=sales.models.Sales.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='items.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(limit_choices_to=sales.models.Sales.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='items.items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='receipt',
            field=models.ForeignKey(limit_choices_to=sales.models.Sales.limit_choices_to_current_user, on_delete=django.db.models.deletion.RESTRICT, to='sales.receipts', verbose_name='Receipt'),
        ),
    ]
